name: Test, build and push Docker image

on:
  push:
    branches:
      - "**"
    tags:
      - "v*.*.*"

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Run tests
        run: cd test && ./run.sh && cd ..

    # TODO: build and push Docker image
